name: francesca
favicon: null
layout_spectrum: 0.28676842944696546
typography_spectrum: 0.35379030578769743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9176954322028905
  lightness: 0.12180384900420904
  saturation: 0.2281217898707837
  rhythmicContrast: 0.01721802749671042
purpose: []
