name: francesca
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5412186
  brandStrength: 0.3154122
  lightness: 0.5376344
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.5591398
typography_spectrum: 0.5286738
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.02329749
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
