favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5412186
  brandStrength: 0.5053763
  lightness: 0.5376344
  brandColors:
    - '#674A08'
    - '#4A77B2'
    - '#0D1007'
    - '#FED430'
    - '#FF4D6C'
  rhythmicContrast: 0.5591398
typography_spectrum: 0.5107527
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9480287
name: francesca
