name: francesca
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5412186
  brandStrength: 0.7007169
  lightness: 0.5376344
  brandColors:
    - '#7686A7'
    - '#8FC9F1'
    - '#19191B'
    - '#253856'
    - '#FDFFFF'
  rhythmicContrast: 0.5591398
typography_spectrum: 0.5286738
layout_spectrum: 0.02329749
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
